apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
	name: mongodb-credentials
	namespace: mongodb
	annotations:
		argocd.argoproj.io/sync-wave: "0"
spec:
	refreshInterval: 1h
	secretStoreRef:
		name: external-secrets-store
		kind: ClusterSecretStore
	target:
		name: mongodb-credentials
		creationPolicy: Owner
	data:
		- secretKey: username
			remoteRef:
				key: mongodb/credentials
				property: username
		- secretKey: password
			remoteRef:
				key: mongodb/credentials
				property: password
